name: Build & Deploy
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore file timestamps
        run: git ls-files | while read file; do touch -d $(git log -1 --format="@%ct" "$file") "$file"; done

      - name: Install fonts
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fonts-noto fonts-noto-cjk
          version: 1.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cache build data
        uses: actions/cache@v3
        with:
          path: .cache
          key: build-cache-v3-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-cache-v3-

      - name: Build site
        run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './public'
          production-branch: main
          functions-dir: './functions'
          deploy-message: ${{ github.event.head_commit.message }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1